# Generated by Django 2.1.7 on 2019-04-05 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekdays_booked', models.BinaryField(default=127, verbose_name=7)),
            ],
        ),
        migrations.CreateModel(
            name='CarPark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('total_parks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReservedBay',
            fields=[
                ('bay_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('car_park_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_alex.CarPark')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='bay_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking_alex.ReservedBay'),
        ),
        migrations.AddField(
            model_name='booking',
            name='car_park_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_alex.CarPark'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_alex.Customer'),
        ),
        migrations.AlterUniqueTogether(
            name='reservedbay',
            unique_together={('car_park_id', 'bay_id')},
        ),
    ]
