# Generated by Django 2.2 on 2019-04-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bay',
            name='size',
            field=models.CharField(default='Any', max_length=10),
        ),
        migrations.AlterField(
            model_name='bay',
            name='code',
            field=models.CharField(blank=True, help_text='A lot-specific code to use for reserved bays. This should not be set on non-reserved bays.', max_length=5, null=True),
        ),
    ]
