# Generated by Django 2.2 on 2019-04-05 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_lotday_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='daily_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='days',
            field=models.ManyToManyField(related_name='bookings', to='parking.LotDay'),
        ),
        migrations.AlterField(
            model_name='lotday',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='parking.Lot'),
        ),
    ]
