# Generated by Django 2.2 on 2019-04-09 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20190409_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='parking.Lot'),
            preserve_default=False,
        ),
    ]
