# Generated by Django 2.2 on 2019-04-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_booking_lot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bay',
            old_name='code',
            new_name='reservation_code',
        ),
        migrations.AddField(
            model_name='bay',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, help_text='A lot-specific bay number.'),
        ),
    ]
