# Generated by Django 2.1.7 on 2019-04-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_auto_20190406_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarParkView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
